asm:
	arm-linux-gnueabi-gcc -S -march=armv7 -o Compilado/fpga_gpu.s fpga_gpu.c 
	arm-linux-gnueabi-gcc -S -march=armv7 -O1 -o Compilado/fpga_gpu_O1.s fpga_gpu.c 
	arm-linux-gnueabi-gcc -S -march=armv7 -O2 -o Compilado/fpga_gpu_O2.s fpga_gpu.c 
	arm-linux-gnueabi-gcc -S -march=armv7 -O3 -o Compilado/fpga_gpu_O3.s fpga_gpu.c 

